server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        namespace: 7f2be4fc-8487-4975-a2eb-6da782e228d5
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** #路径断言，判断路径是否以/user开头，如果是则符合
        - id: chat-service
          uri: lb://chatservice
          predicates:
            - Path=/order/**
#          filters:
#            - AddRequestHeader=Truth,Itcast is awesome!
      default-filters:
        - AddRequestHeader=Truth,Itcast is awesome!
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        crosConfiguration:
          '[/**]':
            allwoedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 36000 #这次跨域检测的有效期

