server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        namespace: 7f2be4fc-8487-4975-a2eb-6da782e228d5
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** #路径断言，判断路径是否以/user开头，如果是则符合
        - id: chat-service
          uri: lb://chatservice
          predicates:
            - Path=/order/**
#          filters:
#            - AddRequestHeader=Truth,Itcast is awesome!
      default-filters:
        - AddRequestHeader=Truth,Itcast is awesome!