logging:
  level:
    cdu.gu: debug
spring:
#  application:
#    name: user
  datasource:
    username: root
    password: 179220
    url: jdbc:mysql://localhost:3306/javaee?serverTimezone=GMT%2B8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#  cloud:
#    nacos:
#      server-addr: localhost:8848 #nacos服务地址
#      discovery:
#        cluster-name: SH
server:
  port: 8081

mybatis:
  type-aliases-package: cdu.gu.entity
  mapper-locations: classpath:mapper/*.xml
#eureka:
#  client:
#    service-url: #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka